export const REQUEST_AUTH = "REQUEST_AUTH";
export const REQUEST_AUTH_SUCCESS = "REQUEST_AUTH_SUCCESS";
export const REQUEST_AUTH_ERROR = "REQUEST_AUTH_ERROR";
export const REQUEST_REGISTER = "REQUEST_REGISTER";
export const REQUEST_REGISTER_SUCCESS = "REQUEST_REGISTER_SUCCESS";
export const REQUEST_REGISTER_ERROR = "REQUEST_REGISTER_ERROR";